# Generated by Django 2.2.6 on 2019-10-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bwm_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_image', models.FileField(upload_to='', verbose_name='original_image')),
                ('wm', models.FileField(upload_to='', verbose_name='water_marking')),
                ('e_image', models.FileField(upload_to='', verbose_name='encode_image')),
                ('d_image', models.FileField(upload_to='', verbose_name='decode_image')),
            ],
        ),
    ]
