# Generated by Django 2.2.6 on 2019-10-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=32, verbose_name='image_name')),
                ('image_type', models.CharField(max_length=32, verbose_name='image_type')),
                ('image', models.FileField(upload_to='', verbose_name='image')),
            ],
        ),
        migrations.DeleteModel(
            name='bwm_image',
        ),
    ]
